name: flower_shop

profile: flower_shop

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  flower_shop:
    +schema: raw
    customers:
      +column_types:
        signup_date: Date
    flowers:
      +column_types:
        price_cents: Int32
    orders:
      +column_types:
        quantity: Int32
        ordered_at: DateTime

models:
  flower_shop:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
