flower_shop:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: flower_shop
      host: localhost
      port: 8123
      user: clickhouse
      password: clickhouse
      secure: false
      threads: 1
